FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

ARG VITE_BASE_URL=/api
ENV VITE_BASE_URL=$VITE_BASE_URL

COPY . .

RUN rm -rf dist && npm run build

FROM nginx:alpine

COPY --from=0 /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]